### ISSUE TITLE
UE 5.1 Support 

### ISSUE THREAD

**Issue by iamsince1998** [whoisEllie/FPS-Core#1]
Hi,
When are you going to update this for ue5.1

**Comment by whoisEllie** [comment]
Hi! UE5.1 support should be coming in just a couple of days (this weekend). I haven't had the chance to work on the project properly since late November, but this will finally change on Friday with the completion of my exams :) Getting FPS Core to work with UE5.1 will be my top priority!

**Comment by whoisEllie** [comment]
Should work with 5.1 now!
